import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { ConvexClientProvider } from "@/components/convex-client-provider"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Slack Clone",
  description: "Generated by create next app"
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  )
}

export default RootLayout
